import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
<link rel="icon" href="/icon?<generated>" type="image/png" sizes="32x32" />
export const metadata: Metadata = {
  title: 'SRK Interiors',
  description: 'Generated by Rahul Mishra',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
